language: rust
sudo: false
rust: nightly

matrix:
  fast_finish: true
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      name: "x86_64-unknown-linux-gnu"
    - env: TARGET=x86_64-apple-darwin
      name: "x86_64-apple-darwin"
      os: osx
      osx_image: xcode9.4

script: cargo test

notifications:
  email:
    on_success: never
